name: Semantic Release
run-name: Semantic Release by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
